origin_z: 0.0
z_resolution: 1
z_voxels: 2

update_frequency: 10.0
publish_frequency: 5.0
transform_tolerance: 1

obstacle_range: 2.5
raytrace_range: 3.0
resolution: 0.05
meter_scoring: true

footprint: [[-0.2, -0.2], [-0.2, 0.2], [0.2, 0.2], [0.2, -0.2]]
footprint_padding: 0.01

static_layer:
   map_topic: /map
   subscribe_to_updates: true

inflater_layer:
   inflation_radius: 0.20


obstacles_layer:
  observation_sources: scan
  scan: {sensor_frame: lidar, data_type: LaserScan, topic: /scan, marking: true, clearing: true, min_obstacle_height: -2.0, max_obstacle_height: 2.0, obstacle_range: 2.5, raytrace_range: 3.0}

  # obstacles_layer:
  #     observation_sources: laser
  #     laser: {data_type: LaserScan, clearing: true, marking: true, topic: scan, inf_is_valid: true}