
type: "diff_drive_controller/DiffDriveController"
publish_rate: 10

# left_wheel: ['left_front_wheel_hinge', 'left_middle_wheel_hinge', 'left_back_wheel_hinge']
# right_wheel:  ['right_front_wheel_hinge', 'right_middle_wheel_hinge', 'right_back_wheel_hinge']
# wheel_separation: 0.33 
left_wheel: 'left_middle_wheel_hinge'
right_wheel:  'right_middle_wheel_hinge'
wheel_separation: 0.25


# Odometry covariances for the encoder output of the robot. These values should
# be tuned to your robot's sample odometry data, but these values are a good place
# to start
pose_covariance_diagonal: [0.001, 0.001, 0.1, 0.1, 0.1, 0.03]
twist_covariance_diagonal: [0.001, 0.001, 0.001, 0.1, 0.1, 0.03]
# pose_covariance_diagonal: [0.001, 0.001, 1000000.0, 1000000.0, 1000000.0, 0.03]
# wist_covariance_diagonal: [0.001, 0.001, 0.001, 1000000.0, 1000000.0, 0.03]

# Top level frame (link) of the robot description
base_frame_id: base_footprint

# Velocity and acceleration limits for the robot
linear:
  x:
    has_velocity_limits    : true
    max_velocity           : 1   # m/s
    has_acceleration_limits: true
    max_acceleration       : 3.0   # m/s^2
angular:
  z:
    has_velocity_limits    : true
    max_velocity           : 2.0   # rad/s
    has_acceleration_limits: true
    max_acceleration       : 4.0   # rad/s^2
    
    
    
enable_odom_tf: false