# global_costmap:
#   global_frame: map
#   robot_base_frame: base_footprint
#   update_frequency: 5.0
#   static_map: true

global_costmap:
   global_frame: map
   robot_base_frame: base_footprint
   # update_frequency: 10.0
   # publish_frequency: 10.0
   width: 100.0
   height: 100.0
   resolution: 0.1
   origin_x: -50.0
   origin_y: -50.0
   # static_map: false
   rolling_window: true

   plugins:
      - {name: static_layer, type: "costmap_2d::StaticLayer"}
      - {name: inflater_layer, type: "costmap_2d::InflationLayer"} 




  #  The "static_map" parameter determines whether or not the costmap should initialize 
  #  itself based on a map served by the map_server. If you aren't using an existing map
  #  \ or map server, set the static_map parameter to false