shutdown_costmaps: false

controller_frequency: 20.0
controller_patience: 15.0

#zmienione za planne_frequency na 0.0, bo https://answers.ros.org/question/247116/how-can-i-reduce-drift-in-my-robots-trajectory/
planner_frequency: 20.0
planner_patience: 5.0

oscillation_timeout: 0.0
oscillation_distance: 0.5

recovery_behavior_enabled: true
clearing_rotation_allowed: true